Add 2023 osaka 1st
perl-entrance-org/perl-entrance-org.github.com pull request #116
Opened 2023-07-11 13:25 UTC by tomcha

8/26のin大阪告知を追加

2023-07-11 13:56 UTC, xtetsuji requested changes
@tomcha 更新作業ありがとうございます！

VILLENT の新予約サイト移行に伴って、upnow → sugurun したほうが良いかなというところ、コメントしてみました :bow:

2023-07-11 13:56 UTC, xtetsuji commented on article/index.md
>              <p class="date" data-date="2023-07-15T00:00:00+09:00">
ついつい忘れがちな箇所ですが、こちらでお願いします〜！

```suggestion
            <p class="date" data-date="2023-08-26T00:00:00+09:00">
```

東京でも忘れがちなので、これの要素の内容を直接 `$(this).text().trim().match(/(\d+)年(\d+)月(\d+)日/)` とかで解釈するでもいいかも……。

2023-07-11 13:56 UTC, xtetsuji commented on article/index.md
> +                    <td><a href="https://upnow.jp/kuraya59/Nishiumeda2" target="_blank">VILLENT西梅田ブルー</a></td>
upnow の予約サイトは9月末までなので、次回以降に備えて

```suggestion
                    <td><a href="https://app.sugurun.jp/VILLENT/007" target="_blank">VILLENT西梅田ブルー</a></td>
```

しておいてもいいかもしれませんね。

今回初めて、この sugurun の予約サイトを使用しました。

メモ：オレンジの方は https://app.sugurun.jp/VILLENT/006 です。

2023-07-11 23:14 UTC, tomcha commented on article/index.md
> +                    <td><a href="https://upnow.jp/kuraya59/Nishiumeda2" target="_blank">VILLENT西梅田ブルー</a></td>
ありがとうございます。リンク先をsugurunのサイトに移行します。

2023-07-12 03:07 UTC, xtetsuji approved these changes
@tomcha ありがとうございます！マージします :+1:

2023-07-12 03:07 UTC, merged