Add perl hackers hub link
perl-entrance-org/perl-entrance-org.github.com pull request #91
Opened 2022-05-23 11:03 UTC by tomcha

AmazonのWEB+DB Vol.128への画像リンクと説明文を付け加えました。
一度見て、ここからどうすれば良いかアドバイスお願いします。

2022-05-23 14:27 UTC, xtetsuji requested changes
@tomcha 修正ありがとうございます！

ちょっと試してうまく配置できなかったのですが、ちゃんと右側に配置されている！しかも書影PNGもファイルサイズ的にちょうどよい大きさですね。

リンクと文言で軽微な点が気になったのでコメントしました。

2022-05-23 14:27 UTC, xtetsuji commented on share/tmpl/index.tx
> +            <a href="https://www.amazon.co.jp/WEB-DB-PRESS-Vol-128-PRESS%E7%B7%A8%E9%9B%86%E9%83%A8-ebook/dp/B09Y8BF6T7/ref=sr_1_1?qid=1653261343&s=books&sr=1-1"><img src="/static/images/web_db128.pn
リンク、技術評論社の公式サイト https://gihyo.jp/magazine/wdpress/archive/2022/vol128 の方が、Amazon 以外から購入したい人も各種書籍販売サイトから飛べたりするので、いいかなと思いました。

理由があって書影を Amazon のリンクにするということであれば、上の紹介文言の「WEB+DB PRESS Vol.128」部分に技術評論社の当該ページへのリンクを設定するのも良さそうです。あと、Amazon のリンクを使う際は、不要部分を短縮した https://www.amazon.co.jp/dp/B09Y8BF6T7/ にしたいです。

2022-05-23 14:27 UTC, xtetsuji commented on share/tmpl/index.tx
> +            <h4>WEB+DB PRESS Vol.128 の連載記事 「Perl Hackers Hub」 に Perl入学式の記事が掲載されました！</h4>
記事という単語が重複しているので、後半から外しても意味が通るから削除しちゃっていいかな…というのと、書籍の出版日を掲載して以下のようにしたいと思ったのですが、どうでしょうか！？

```suggestion
            <h4>WEB+DB PRESS Vol.128 の連載記事 「Perl Hackers Hub」 に Perl入学式が掲載されました！</h4>
```

新しい雑誌であることを強調するために、2022年4月23日発売であることも入れいたいと思ったのですが、少々冗長かなと思って悩んでいます。いったん入れなくてもいいかな。

2022-05-23 23:03 UTC, tomcha commented on share/tmpl/index.tx
> +            <h4>WEB+DB PRESS Vol.128 の連載記事 「Perl Hackers Hub」 に Perl入学式の記事が掲載されました！</h4>
いつ頃の雑誌なのか、情報は入れた方がよさそうですね。2022年4月発売を追加してみます

2022-05-24 02:12 UTC, xtetsuji approved these changes
修正ありがとうございます！サイト反映します。

2022-05-24 02:12 UTC, merged