Change 2022 osaka 1st
perl-entrance-org/perl-entrance-org.github.com pull request #97
Opened 2022-07-29 08:38 UTC by tomcha

2022in大阪の告知を追加しました。

2022-07-29 11:04 UTC, xtetsuji requested changes
@tomcha 修正ありがとうございます！

気になった点にコメントしてみました。

2022-07-29 11:04 UTC, xtetsuji commented on article/index.md
> +                <dt>2022.7.29</dt>
公開日時、週明けになるようでしたら 2022.8.1 にしておくと良かったりしますかね……？

2022-07-29 11:57 UTC, tomcha commented on article/index.md
> +            <p class="date" data-date="2022-09-3T00:00:00+09:00">
ありがとうございます。修正します。

2022-07-29 11:57 UTC, tomcha commented on article/index.md
> +                <dt>2022.7.29</dt>
そうですね。8.1へ修正します。

2022-07-30 08:26 UTC, xtetsuji reviewed
修正ありがとうございますー！Approve します。

2022-07-30 08:26 UTC, xtetsuji approved these changes

2022-07-30 08:30 UTC, xtetsuji commented
GitHub 謎挙動で勝手に送信されてしまってコメント書き損なったのですが、私の方でマージはしないので @tomcha さんの方で8月1日にマージ下さい。

手元で `riji server` してプレビューしてみたのですが、現在活動しているin大阪を上部に引き上げても良いかなと思ったり。これはミーティングで議論して、必要であれば別プルリクで対応しましょう。

2022-07-31 22:54 UTC, merged